version: '3.8'

services:

  # ===============================
  # USER SERVICE
  # ===============================
  user-service:
    build: .
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/userdb
      DB_USER: postgres
      DB_PASS: postgres
      JWT_SECRET: 46294A404E635266556A586E32723575
      SPRING_PROFILES_ACTIVE: docker

  # ===============================
  # POSTGRES
  # ===============================
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ===============================
  # KAFKA (KRaft mode - no zookeeper)
  # ===============================
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Enable KRaft
      KAFKA_ENABLE_KRAFT: "yes"

      # Node roles
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 1

      # Controller quorum
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Listeners
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      # Controller listener
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Single node safe configs
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  postgres_data:
  kafka_data: